### PR TITLE
created holes for tetrahedralize(::Mesh, ...)

### PR DESCRIPTION
**Pull request by chakravala**
see issue #17

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Thank you!
Do you have some code handy to test this?

**Comment by chakravala** [comment]
Any update on this? I forgot what my code was to test this, but maybe I'll take another look sometime if it helps complete this PR.

**Comment by SimonDanisch** [comment]
Yeah hard to tell if it works without a test ;) I don't really know tetgen  very well... Tagging @j-fu for a review!

**Comment by chakravala** [comment]
Alright, I do have a test which works, but it requires a whole bunch of dependencies (my `Grassmann` and `FlowGeometry` and also other packages like `MiniQhull`). So these tests are not suitable for putting into this repository. However, I can assure you that this change I made enables hole syntax.

In my example, I first generate some data using `FlowGeometry.cubesphere()` to generate the points of a sphere inside a cube. Then after generating those points, I can pass them onto
```
result = tetrahedralize(FlowGeometry.cubesphere(), "vpq1.414a0.1";holes=[TetGen.Point(0.0,0.0,0.0)])`
```
This example is too complex to really share with you, so @j-fu need to come up with your own simpler example, as I don't know how you prefer to generate examples for this repository.

**Comment by j-fu** [comment]
Essentially, this repo contains  two APIs for TetGen, one which is based on GeometryBasics.Mesh which AFAIU does not convey all possibilities of TetGen.  I added another API (after your PR) which is essentially array based (very much like that  for Triangulate.jl).  It is not hard for me to provide a hole example for this one, and from there you can see how to make a hole example for the mesh based API.

**Comment by SimonDanisch** [comment]
>GeometryBasics.Mesh which AFAIU does not convey all possibilities of TetGen

Which cases are those?

**Comment by chakravala** [comment]
Sounds good to me, I don't really need the example personally, and I don't necessarily need this PR to be merged either, as I also have my own mesh API built into my `Grassmann` package, and I already have a custom `tetrahedralize` command for my own mesh API based on `Grassmann`, which does not depend on merging this PR.

This PR is just a courtesy to help you understand the simple changes needed to `tetrahedralize` to enable `holes` syntax.

**Comment by chakravala** [comment]
> > GeometryBasics.Mesh which AFAIU does not convey all possibilities of TetGen
> 
> Which cases are those?

An example is what I just explained above: `GeometryBasics.Mesh` does not specify `holes` in it, which is a `TetGen` feature.

**Comment by j-fu** [comment]
Hi, just pushed an example how to serve the TetGen API:
https://github.com/JuliaGeometry/TetGen.jl/blob/b4f6630025b5fc63c2c2d598ff65689dc4c7c836/examples/examples.jl#L49

One needs to create  subregion encircled by facets an put a "holepoint" into it.
See also  http://wias-berlin.de/software/tetgen/1.5/doc/manual/manual006.html#ff_poly
and https://juliageometry.github.io/TetGen.jl/stable/#TetGen.RawTetGenIO

**Comment by j-fu** [comment]
> > GeometryBasics.Mesh which AFAIU does not convey all possibilities of TetGen
> 
> Which cases are those?
May I miss something  due to insufficient knowledge how to work with the mesh struct so please correct me on that:
What comes into my mind  in addition to holes:
-  different cell region markers: instead of a hole point I can place  a "region point" and spread its marker (and a maximal volume) to a whole subregion, creating some integer "cell meta" on output,  very much like boundary facet markers
- local refinement via callback (but this of course wouldn't go into the Mesh API I think it already now could be used together with it)

**Comment by chakravala** [comment]
However, this pull request does address the `holes` issue for `tetrahedralize` with `GeometryBasics.Mesh` inputs by providing the keyword `holes` as an extra argument. This is the least amount of work solution possible to resolve the compatibility issue.

**Review by j-fu — APPROVED** [review]

**Comment by j-fu** [comment]
Will add a test example after merge.

**Comment by SimonDanisch** [comment]
Alright, thanks :)

**Comment by chakravala** [comment]
Please deliver a message to the Julia Stewards for me, they are a bunch of shitbag assholes who are harming the development of open source software. Sorry to pollute the discussion with this again.

We are lucky that neither of you are part of the Julia Stewards gang of assholes, otherwise you would not have been able to accept this pull request for this repository, as they banned me from participating on a bunch of github organization.

I hope the Julia Stewards all go to hell for the harm they're causing to the development of open source software.

**Pull request merged**
